### ISSUE TITLE
Connection establishing prinout

### ISSUE THREAD

**Issue by fallion** [nats-io/nats.ex#104]
Hi,

Currently the connection prinout here https://github.com/nats-io/nats.ex/blob/f2accd13a65c751543cb44df367ac43fd93071ae/lib/gnat/connection_supervisor.ex#L60 uses `Logger.info`, this means that if you are deploying this with authentication enabled you will print the secrets into std.out unless you are silencing all info messages. 

I have the following proposals:
- change it to Logger.debug

OR

- strip any secret data from this printout so that the URL, PORT, AUTH_REQUIRED and any other non-secret info gets printed

Thanks for any other suggestions or help :) We're already using this in production for one of our apps.

**Comment by mmmries** [comment]
@fallion this is a great point. I'll try to get this patched shortly

**Comment by fallion** [comment]
I can make the PR if you want. Just curious about which solution you would go for. :)

**Comment by mmmries** [comment]
I think `Logger.debug` is the easiest solution and it probably makes sense since you don't need that information in production logs
