### ISSUE TITLE
Outdated Changelog

### ISSUE THREAD

**Issue by kianmeng** [nats-io/nats.ex#109]
The current `CHANGELOG.md` file have not been updated since version 6.0 release. It would be useful and helpful to let the developer have an overview of changes for each released version.

**Comment by mmmries** [comment]
Yes, updating the CHANGELOG would definitely be useful for people wanting to use the library. I've been letting it slip, but I'm starting to use this project in my own job again so I should have some more time to dedicate to it.

Is there anything in-particular that you like to see in a CHANGELOG?

**Comment by mmmries** [comment]
I got the CHANGELOG populated with summaries from 0.7 - 1.2
