### ISSUE TITLE
Relax or update nimble_parsec dep

### ISSUE THREAD

**Issue by cjbottaro** [nats-io/nats.ex#112]
Need it to be "~> 1.0" because of a bunch of other deps. Thanks!

**Comment by mmmries** [comment]
Thanks for the issue. I hadn't kept up with the `nimble_parsec` project, but I'll go test against the `1.X` versions and see if we can accept something like `~> 0.5 or ~> 1.0`

**Comment by mmmries** [comment]
Released as version `1.2.1` ❤️ 💛 💙 💚 💜

I'd love to hear about how you're using it if you have a minute to drop a quick description

**Comment by cjbottaro** [comment]
@mmmries We're considering replacing our fanout exchange queuing system with streams. So I was going to implement the streaming protocol with this library.

I actually implemented both Nats and Nats Streaming in Elixir years ago, but I lost the code... :) The protocol is so simple though, it took me about an hour to implement a Nats client last night. It's like working with RESP. 👍

**Comment by mmmries** [comment]
I'm looking into Jetstream for my job too. Just waiting for the first general release. I got started on a library that works with this one to handle the jetstream protocol if you're interested https://github.com/mmmries/jetstream
