### ISSUE TITLE
add Headers Support

### ISSUE THREAD

**Issue by byu** [nats-io/nats.ex#115]
Nats 2.2+ has added new protocol for publishing/subscribing messages w/ http-like headers.
it would be nice for this client lib to support this new protocol.

**Comment by mmmries** [comment]
💯 I would love to add support for headers here. I'm planning to add it before too long, but if anyone else wants to take a crack at it first I would take a look at the `lib/gnat/parsec.ex` file which we use to parse the raw TCP bytes into message structs.

**Comment by mmmries** [comment]
I started to look into this and @wallyqs pointed me to https://github.com/nats-io/nats-server/blob/be9fb5f6f2455c40691260986bdb37b1e5796046/doc/adr/0004-nats-headers.md which documents how to support headers.

I'll try to take a crack at this soon, but if anyone wants to start on it before I do, I can help point you in the right direction

**Comment by autodidaddict** [comment]
Just came here to second the need/desire for headers as I've got Go and Rust clients attempting to send my Elixir code messages with headers.

**Comment by mmmries** [comment]
Hey @autodidaddict any chance you can try out the `1.3.0-rc0` release to see if that matches your needs? I'm leaning towards releasing those changes, but was just wanting to wait for some feedback

**Comment by autodidaddict** [comment]
Looking at the [docs](https://hexdocs.pm/gnat/1.3.0-rc0/Gnat.html#t:message/0) for the `message()` type for 1.3.0-rc0 doesn't show any header support. Is there somewhere else I should be looking for it?

**Comment by autodidaddict** [comment]
@mmmries also looking at the source code and not finding out how to set/read the headers on message publications through `request` or through `pub`. This is likely due to me not understanding what I'm looking for/at, but if you could point me at some sample code that uses headers in both directions, that would be amazing.

**Comment by mmmries** [comment]
@autodidaddict I haven't written up changes to the docs yet, but here is what changes for `1.3.0-rc0`

* headers are represented as a list of tuples (this allows repeated keys). `[{"header name", "header value"}, ...]`
* when receiving a message that was sent with headers, you'll get a map that includes a `:headers` key a list of headers, this key will only be present for messages published with headers, it is omitted for normal messages
* When calling `pub` you can pass an optional `:headers` key in the`opts` 4th argument
* When calling `request` you can pass an optional `:headers` key in the `opts` 4th argument

**Comment by autodidaddict** [comment]
Awesome that sounds like exactly what we've want to do with headers

**Comment by mmmries** [comment]
Version 1.3.0 has been released with some improved documentation and all of these changes discussed. ❤️ 💛 💙 💚 💜

Thanks for the nudges and verification!
