### ISSUE TITLE
IPv6 Support?

### ISSUE THREAD

**Issue by jasonbarbee** [nats-io/nats.ex#129]
I'm in a situation where I need ipv6 to reach a NATS cluster, and cannot use ipv4 to reach it. 

NATs currently only calls ipv4, and doesn't have any flag to enable ipv6 that I see.

Any chance you could add a config option in start_link and the Connection Settings config block for passing ipv6 flag down to gen_tcp:connect?
Here's an example of making an ipv6 connection, it just needs that extra socket options parameter to pass to gen_tcp. 

{ok, conn} = gen_tcp:connect("ipv6.google.com", 80, [inet6])

Thanks for considering,

**Comment by mmmries** [comment]
Yes! I'll definitely add support for that, let me see if I can get a unit test setup to cover this use-case

**Comment by mmmries** [comment]
Oh, it looks like this is already supported via the `tcp_opts` argument which allows you to pass any custom options you want to the nats TCP connection.

I tested this by starting up a nats server like this:

```
$ nats-server -a ::1 -p 4248
```

Then I opened a connection like this:

```elixir
{:ok, pid} = Gnat.start_link(%{host: '::1', port:4248, tcp_opts: [:binary, :inet6]})
```

> ⚠️  Make sure you always include `:binary` when setting `:tcp_opts`

I'll write up a quick note in the documentation to cover this use-case.

**Comment by jasonbarbee** [comment]
Exactly. I was just posting an update, that I did get it working as above.
A minor note in the docs would be perfect. Thanks!

**Comment by mmmries** [comment]
Okay, merged my PR to add a doc for this and pushed the latest hexdocs out https://hexdocs.pm/gnat/1.5.2/Gnat.html#start_link/2

**Comment by mmmries** [comment]
❤️ 💛 💙 💚 💜 Thanks for surfacing this issue!
