### ISSUE TITLE
Add official release from tag

### ISSUE THREAD

**Issue by bruth** [nats-io/nats.ex#140]
@mmmries I am building up a new NATS clients download page which relies on fetching info from the GitHub API to populate the page. Would you mind creating a GitHub release for the latest tag and then doing that going forward?

**Comment by mmmries** [comment]
I haven't worked with github releases before, but I'll check into it this week

**Comment by bruth** [comment]
No worries, thanks. The simplest approach is to create one from a tag.
<img width="657" alt="image" src="https://github.com/nats-io/nats.ex/assets/515142/e86fbdfb-a252-4a39-8aeb-5e3e99d7fbe6">

Then write a short description or "Generate Release Notes" then publish.

<img width="648" alt="image" src="https://github.com/nats-io/nats.ex/assets/515142/5d42796d-87c9-46fa-b58c-29dd54c1ae6e">

**Comment by mmmries** [comment]
I went back and added tags for v1.5.1, v1.5.2 and made releases for 1.5.2 and 1.6.0

I'll try to make sure we create these releases for future versions. I don't think anyone in the Elixir community will actually use these releases. The community will all use the tooling around hex.pm instead.
