### ISSUE TITLE
Function clause error on INFO message

### ISSUE THREAD

**Issue by 0xAX** [nats-io/nats.ex#174]
Hello,

I am experimenting with catching of restart/upgrade of NATS server to re-establish connections by catching 'EXIT' from Gnat.start_link and trying to start it again. After some succesfull restarts I start to see the following error:

```
{error,{function_clause,[{'Elixir.Gnat.Parsec',command,["INFO {\"server_id\":\"NAZRHVUEQEZFZONKORUIVOZI3GYIVR65RTMF2WI2RVM3OHF7EGCNAKWF\",\"server_name\":\"nats-0\",\"version\":\"2.10.21\",\"proto\":1,\"git_commit\":\"d3a8868\",\"go\":\"go1.22.7\",\"host\":\"0.0.0.0\",\"port\":4222,\"headers\":true,\"max_payload\":1048576,\"jetstream\":true,\"client_id\":12602,\"client_ip\":\"10.42.241.62\",\"xkey\":\"XBRV2OPJEHEGVZNF6Q7PY7NFUUWBWNZ7GR5W2XS3EDPFSYFRDYMEGQQ3\"} \r\n",[]],[{file,"lib/gnat/parsec.ex"},{line,73}]},{'Elixir.Gnat.Parsec',parse_command,1,[{file,"lib/gnat/parsec.ex"},{line,96}]},{'Elixir.Gnat.Parsec',parse_commands,2,[{file,"lib/gnat/parsec.ex"},{line,88}]},{'Elixir.Gnat.Parsec',parse,2,[{file,"lib/gnat/parsec.ex"},{line,78}]},{'Elixir.Gnat.Handshake',perform_handshake,2,[{file,"lib/gnat/handshake.ex"},{line,27}]},{'Elixir.Gnat',init,1,[{file,"iex"},{line,399}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]}]}}.
```

is there any ideas what could it be?

Let me please know if you are interested additional details

**Comment by 0xAX** [comment]
The error is happening only if I am using `tcp_opts`:

```
Gnat.start_link(%{host: addr, port: port, tcp_opts: [{:send_timeout, 5000}, {:send_timeout_close, true}]})
```

**Comment by 0xAX** [comment]
ah sorry, didn't note:

> If you pass custom TCP options please include `:binary`. Gnat uses binary matching to parse messages.

**Comment by mmmries** [comment]
@0xAX thanks for opening the issue and following up with your findings. Maybe we should raise an error when passing in `tcp_opts` without the binary flag? Seems like it would have made life a lot easier for you?

**Comment by mmmries** [comment]
Also, have you looked into [Gnat.ConnectionSupervisor](https://hexdocs.pm/gnat/Gnat.ConnectionSupervisor.html) it provides a basic monitoring and restart capability
