### ISSUE TITLE
wrong value for `two_minutes_in_nanoseconds`

### ISSUE THREAD

**Issue by RoadRunnr** [nats-io/nats.ex#175]
here:

https://github.com/nats-io/nats.ex/blob/cc237c00546eb206199698be1933a46d04fbdfde/lib/gnat/jetstream/api/kv.ex#L11

There are 10^9 nanoseconds in one second, correct value is therefore `120_000_000_000` or `2 * 60 * 1_000_000_000`

**Comment by mmmries** [comment]
Thanks for spotting that issue! I'll get it fixed in #176

**Comment by mmmries** [comment]
This was fixed in #176 and released in version 1.9.0 ❤️ 💛 💙 💚 💜 

Thanks again for finding and reporting this issue
