### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by namxam** [nats-io/nats.ex#91]
Are there any plans to support streaming? I saw a closed #90 and it mentions a separate package. But I could not find anything related. Would be nice to have a streaming client.

**Comment by mmmries** [comment]
👋 Hi @namxam,
I worked on nats streaming a few months ago and got to a point where I had basic publishing and subscription supported. All of that code is pushed up to https://github.com/mmmries/nats.ex_streaming

Would you mind trying that code out to see if it works well for your use-case or what it might be missing? I'm not currently using nats-streaming for any of my work projects so I was unsure of whether the API was in a good place.

**Comment by namxam** [comment]
Nice, I read it in your PR, but haven't found the repo. Sorry about that. I am quite new to NATS and especially NATS Streaming. Anyhow, I will give it a try. I managed to setup a connection, create a subscription and publish/receive messages.

Just a quick question, how do I create a durable subscription? Or should I create issues in the dedicated repo?

**Comment by mmmries** [comment]
Hmmm good question 🤔. I'm not very familiar with nats streaming either. Let's open an issue on that repo so we can discuss durability
