### ISSUE TITLE
Reconnect Functionality

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.ex#94]
Reconnect is currently listed as an experimental feature.  Users have expressed interest in promoting this as a fully supported feature.  We need to evaluate where reconnect functionality is at and how it can be supported as a first class feature of this client.

@mmmries , wdyt?

**Comment by mmmries** [comment]
@ColinSullivan1 thanks for passing this along. We just chatted in slack around this:

<img width="1141" alt="Screen Shot 2020-01-09 at 4 09 28 PM" src="https://user-images.githubusercontent.com/80008/72112303-71c26700-32fa-11ea-99b1-16f4643e690c.png">

The `ConnectionSupervisor` feature that already exists has been in active use for 3+ years in production systems at [MX](https://mx.com) so I think it's pretty solid. I'll try to push up a change removing the "experimental" comment, and I'll clarify that we don't yet have support for dynamic node discovery.
